name: Feature Request
description: Suggest a new feature for ReasonKit
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - Lenvanderhof

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - reasonkit (umbrella)
        - reasonkit-core
        - reasonkit-mem
        - reasonkit-web
        - Documentation
        - Other
    validations:
      required: true
